name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    env:
      workspace: workspace
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
      shell: bash

    - name: Build the devenv shell and run any pre-commit hooks
      run: devenv test

    - name: Set up workspace
      run: edm init --workspace {workspace}

    - name: Run a multi-line command in the devenv shell
      shell: devenv shell bash -e {0}
      run: |
        mkdir {workspace}/build
        cd {workspace}/build
        cmake ..
        make install
