name: "Test"

on:
  pull_request:
  push:

env:
  workspace: "workspace"

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v27
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
      shell: bash

    - name: Set up workspace
      run: edm init --workspace ${workspace}

    - name: Run the build
      shell: devenv shell bash -e {0}
      run: |
        mkdir ${workspace}/build
        cd ${workspace}/build
        cmake ..
        make install
